# Pentest-USB Toolkit - Main Configuration
# =============================================

# Project Information
project:
  name: "Pentest-USB Toolkit"
  version: "1.0.0"
  description: "Comprehensive portable penetration testing framework"
  author: "Pentest-USB Development Team"

# Global Settings
global:
  debug_mode: false
  verbose_logging: false
  max_concurrent_tasks: 4
  timeout_default: 300
  retry_attempts: 3
  
# Directory Paths
paths:
  tools_dir: "./tools/binaries"
  data_dir: "./data"
  output_dir: "./outputs"
  logs_dir: "./logs"
  reports_dir: "./reports"
  temp_dir: "./outputs/temporary"

# Network Configuration
network:
  user_agent: "Mozilla/5.0 (compatible; PentestUSB/1.0)"
  request_timeout: 30
  max_redirects: 5
  verify_ssl: true
  proxy:
    enabled: false
    http_proxy: ""
    https_proxy: ""
    no_proxy: "localhost,127.0.0.1"

# Module Configuration
modules:
  reconnaissance:
    enabled: true
    default_timeout: 600
    max_threads: 8
  
  vulnerability:
    enabled: true
    default_timeout: 1800
    max_threads: 4
    
  exploitation:
    enabled: false  # Requires explicit consent
    default_timeout: 900
    max_threads: 2
    
  post_exploitation:
    enabled: false  # Requires explicit consent
    default_timeout: 600
    max_threads: 1
    
  reporting:
    enabled: true
    default_format: "pdf"
    include_screenshots: true

# Tool Profiles
tool_profiles:
  quick_scan:
    - nmap
    - rustscan
    - nuclei
    
  comprehensive_scan:
    - nmap
    - masscan
    - zap
    - nuclei
    - nikto
    - dirb
    
  stealth_scan:
    - nmap_stealth
    - amass
    - subfinder
    - nuclei

# Resource Limits
resource_limits:
  max_cpu_usage: 80  # percentage
  max_memory_usage: 80  # percentage
  max_disk_usage: 90  # percentage
  min_free_space: 1024  # MB

# Security Settings
security:
  require_consent: true
  audit_all_actions: true
  encrypt_outputs: false
  secure_delete: true
  
# Auto-cleanup
cleanup:
  auto_cleanup_enabled: true
  cleanup_after_hours: 24
  keep_reports: true
  keep_evidence: true