# Configuration Réseau - Pentest-USB Toolkit
# Paramètres réseau pour tous les modules et outils

# Configuration générale du réseau
network:
  # Interfaces réseau par défaut
  interfaces:
    auto_detect: true
    preferred_interface: "auto"    # auto, eth0, wlan0, etc.
    monitor_all_interfaces: true
    
  # Configuration IP
  ip_settings:
    ipv4:
      enabled: true
      prefer_ipv4: true
      
    ipv6:
      enabled: true
      prefer_ipv6: false
      
    # Configuration DHCP
    dhcp:
      enabled: true
      timeout: 30          # secondes
      retry_attempts: 3

# Configuration des scans réseau
scanning:
  # Paramètres généraux de scan
  general:
    default_timeout: 5000        # millisecondes
    max_concurrent_scans: 100
    retry_failed_connections: 3
    adaptive_timing: true
    
  # Configuration des ports
  ports:
    # Ports les plus courants (scan rapide)
    common_ports:
      - 21    # FTP
      - 22    # SSH
      - 23    # Telnet
      - 25    # SMTP
      - 53    # DNS
      - 80    # HTTP
      - 110   # POP3
      - 143   # IMAP
      - 443   # HTTPS
      - 993   # IMAPS
      - 995   # POP3S
      - 3389  # RDP
      - 5432  # PostgreSQL
      - 3306  # MySQL
      
    # Plages de ports pour différents types de scan
    ranges:
      quick: "1-1000"
      standard: "1-65535" 
      common: "21,22,23,25,53,80,110,143,443,993,995,3389"
      
    # Ports par service
    service_ports:
      web: "80,443,8000,8080,8443,8888"
      database: "1433,1521,3306,5432,27017"
      email: "25,110,143,587,993,995"
      remote: "22,23,3389,5900,5901"

# Configuration DNS
dns:
  # Serveurs DNS
  servers:
    primary:
      - "8.8.8.8"           # Google DNS
      - "1.1.1.1"           # Cloudflare DNS
      
    secondary:
      - "8.8.4.4"           # Google DNS secondaire
      - "1.0.0.1"           # Cloudflare DNS secondaire
      
    # Serveurs DNS pour résolution inverse
    reverse_dns:
      enabled: true
      timeout: 3            # secondes
      
  # Configuration de résolution
  resolution:
    timeout: 5              # secondes
    retries: 2
    use_system_resolver: true
    enable_dns_cache: true
    cache_ttl: 300          # secondes

# Configuration des proxies
proxy:
  # Proxy HTTP/HTTPS
  http_proxy:
    enabled: false
    host: ""
    port: 8080
    username: ""
    password: ""
    
  # Proxy SOCKS
  socks_proxy:
    enabled: false
    host: ""
    port: 1080
    version: 5              # 4 ou 5
    
  # Chaîne de proxies (proxy chaining)
  proxy_chains:
    enabled: false
    strict_chain: true      # true pour strict, false pour dynamic
    proxies: []

# Configuration SSL/TLS
ssl_tls:
  # Vérification des certificats
  certificate_verification:
    verify_ssl: true
    verify_hostname: true
    allow_self_signed: false
    
  # Versions SSL/TLS supportées
  supported_versions:
    - "TLSv1.2"
    - "TLSv1.3"
    
  # Chiffrement
  ciphers:
    preferred: "ECDHE-RSA-AES256-GCM-SHA384"
    allowed:
      - "ECDHE-RSA-AES256-GCM-SHA384"
      - "ECDHE-RSA-AES128-GCM-SHA256"
      - "ECDHE-RSA-AES256-SHA384"

# Configuration des User Agents
user_agents:
  # User agents pour les requêtes HTTP
  rotation:
    enabled: true
    random_selection: true
    
  agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"

# Configuration de la bande passante
bandwidth:
  # Limitation de bande passante
  throttling:
    enabled: false
    download_limit: 0       # KB/s (0 = illimité)
    upload_limit: 0         # KB/s (0 = illimité)
    
  # Gestion de la congestion
  congestion_control:
    algorithm: "cubic"      # cubic, reno, bbr
    buffer_size: 65536      # bytes

# Configuration des timeouts
timeouts:
  # Timeouts généraux
  connection:
    tcp_connect: 10         # secondes
    tcp_read: 30           # secondes
    tcp_write: 10          # secondes
    
  # Timeouts HTTP
  http:
    request: 30            # secondes
    response: 60           # secondes
    total: 120             # secondes
    
  # Timeouts DNS
  dns_resolution: 5        # secondes

# Configuration de la détection d'OS et services
os_detection:
  # Fingerprinting TCP/IP
  tcp_fingerprinting:
    enabled: true
    aggressive: false      # scan plus discret si false
    
  # Détection de services
  service_detection:
    enabled: true
    version_intensity: 7   # 0-9 (9 = plus agressif)
    
  # Scripts NSE (Nmap Scripting Engine)
  nse_scripts:
    enabled: true
    categories:
      - "safe"
      - "default"
      - "version"

# Configuration de l'évasion de détection
evasion:
  # Techniques d'évasion réseau
  network_evasion:
    # Fragmentation des paquets
    packet_fragmentation:
      enabled: false
      fragment_size: 8      # bytes
      
    # Leurres (decoy scanning)
    decoy_scanning:
      enabled: false
      max_decoys: 5
      random_decoys: true
      
    # Timing et délais
    timing:
      scan_delay: 0         # millisecondes entre les paquets
      max_retries: 2
      initial_rtt_timeout: 1000  # millisecondes

# Configuration pour différents environnements réseau
environments:
  # Réseau d'entreprise
  corporate:
    respect_rate_limits: true
    use_conservative_timeouts: true
    avoid_aggressive_scans: true
    
  # Réseau domestique
  home:
    full_port_range: true
    aggressive_timing: true
    
  # Réseau public/café
  public:
    use_vpn_recommended: true
    enhanced_privacy: true
    limited_scanning: true

# Logging réseau
logging:
  # Logs de trafic réseau
  network_traffic:
    enabled: true
    level: "INFO"
    capture_headers: true
    capture_payloads: false  # pour la confidentialité
    
  # Logs des connexions
  connections:
    enabled: true
    log_successful: true
    log_failed: true
    log_timeouts: true

# Configuration spécifique aux outils
tool_specific:
  # Configuration pour Nmap
  nmap:
    source_port: 0          # 0 = aléatoire
    data_length: 0          # bytes supplémentaires
    ttl: 0                  # 0 = par défaut
    
  # Configuration pour cURL
  curl:
    follow_redirects: true
    max_redirects: 10
    cookie_jar: "temp/cookies.txt"
    
  # Configuration pour les APIs externes
  external_apis:
    shodan:
      rate_limit: 1         # requêtes par seconde
      timeout: 30           # secondes
      
    virustotal:
      rate_limit: 4         # requêtes par minute
      timeout: 60           # secondes

# Validation de la configuration
validation:
  # Tests de connectivité au démarrage
  connectivity_tests:
    enabled: true
    test_dns: true
    test_http: true
    test_https: true
    
  # Validation des paramètres
  parameter_validation:
    enabled: true
    strict_mode: true